# Generated by Django 4.2.3 on 2023-08-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_historia_clinicamodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia_clinicamodel',
            name='user',
        ),
    ]
