# Generated by Django 4.2.3 on 2023-09-16 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_historia_clinicamodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia_clinicamodel',
            name='perfil_paciente',
        ),
        migrations.RemoveField(
            model_name='perfilpaciente',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Historia_ClinicaModel',
        ),
        migrations.DeleteModel(
            name='PerfilPaciente',
        ),
    ]
