# Generated by Django 4.2.3 on 2023-09-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_remove_historia_clinicamodel_perfil_paciente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultasModel',
        ),
    ]
